name: betalent
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.0.1
  result_dart: ^1.1.1
  flutter_svg: ^2.0.15
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica/Helvetica.ttf
          style: normal
        - asset: assets/fonts/helvetica/Helvetica-Oblique.ttf
          style: italic
        - asset:  assets/fonts/helvetica/helvetica-light.ttf
          weight: 300
        - asset: assets/fonts/helvetica/Helvetica-Bold.ttf
          weight: 800